[project]
name = "identity-registry"
description = "Decentralized Identity Registry Smart Contract"
authors = ["Developer"]
telemetry = false
cache_dir = "./.clarinet"

[contracts.identity-registry]
path = "contracts/identity-registry.clar"
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
parser_version = 2