[network]
name = "simnet"

[accounts.deployer]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"
balance = 100_000_000_000_000

[accounts.wallet_1]
mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen trash pretty park cube fragile unaware remain midnight betray rebuild"
balance = 100_000_000_000_000

[accounts.wallet_2]
mnemonic = "hold excess usual excess ring elephant install account glad dry fragile donkey gaze humble truck breeze nation gasp vacuum limb head keep delay hospital"
balance = 100_000_000_000_000

[accounts.wallet_3]
mnemonic = "cycle puppy glare enroll cost improve round trend wrist mushroom scorpion tower claim oppose clever elephant dinosaur eight problem before frozen dune wagon high"
balance = 100_000_000_000_000

[accounts.wallet_4]
mnemonic = "board list obtain sugar hour worth raven scout denial thunder horse logic fury scorpion fold genuine phrase wealth news aim below celery when cabin"
balance = 100_000_000_000_000

[accounts.wallet_5]
mnemonic = "anchor humble keen detail study shoot foot scan eternal chicken loud exotic matter giant hurdle wash choice park mansion increase hit guide true animal"
balance = 100_000_000_000_000

[accounts.wallet_6]
mnemonic = "spare decline dog guard amused dismiss forget basic resource independence wreck top steel razor believe fish dirt clinic cancer prevent toe claim obvious clinic"
balance = 100_000_000_000_000

[accounts.wallet_7]
mnemonic = "elder tragedy motor ramp affair avocado habit follow pioneer grape hawk shove peace thanks oak castle indicate particle inmate entire relief start cut young"
balance = 100_000_000_000_000

[accounts.wallet_8]
mnemonic = "elephant tail burden melody harvest talk soul plastic look shore midnight glory story rescue produce power universe surface area wide month racket aspect vacant"
balance = 100_000_000_000_000

[accounts.wallet_9]
mnemonic = "peanut large tornado bird scan raw bread education fruit ferry detail style exile hunt west consider paper draft fan service desk spirit humane analyst"
balance = 100_000_000_000_000